import "import-alias/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";

import { TRPCReactProvider } from "import-alias/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <nav className="border-b bg-white">
          <div className="container mx-auto px-6 py-4">
            <div className="flex items-center gap-6">
              <Link href="/" className="text-xl font-bold">
                Planner
              </Link>
              <Link href="/dashboard" className="text-sm hover:text-blue-600">
                Dashboard
              </Link>
            </div>
          </div>
        </nav>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
